# Generated by Django 4.2.7 on 2023-11-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%Y/%m/%d', verbose_name='Video')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='picture/%Y/%m/%d', verbose_name='Picture')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Description')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/%Y/%m/%d', verbose_name='Audio')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.game', verbose_name='Game')),
            ],
        ),
    ]
